### ISSUE TITLE
  Method Illuminate\Support\Str::replace does not exist.

### ISSUE THREAD

**Issue by anonymouse703** [rappasoft/laravel-livewire-tables-docs#5]
How to solve this below error when using this command?
`php artisan make:datatable UserTable User --view`

error

```
 BadMethodCallException 

  Method Illuminate\Support\Str::replace does not exist.
  ```

**Comment by rappasoft** [comment]
That class is part of Laravel I don't know how you don't have it.

**Comment by anonymouse703** [comment]
@rappasoft  yes I know it's Laravel Bug but it triggered when I use this command `php artisan make:datatable UserTable User --view` from your documentation https://rappasoft.github.io/laravel-livewire-tables-docs/start/Commands/

**Comment by rappasoft** [comment]
Ok i'll take a look.
